/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.finaleProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import static my.val.ValidationAndCalculationMethods.*;

/**
 * The {@code StaffForm} class represents a Swing-based form that allows
 * viewing, updating, and printing details of a staff member stored in the
 * database.
 * <p>
 * Main features include:
 * <ul>
 * <li>Loading staff details by ID from the database.</li>
 * <li>Editing staff information and saving changes back to the database.</li>
 * <li>Printing staff details via a separate {@code PrintFrame} window.</li>
 * <li>Navigation options to return to the staff view screen.</li>
 * </ul>
 * <p>
 * This form connects to a MySQL database using JDBC and handles basic input
 * validation for certain fields (letters, digits, etc.).
 *
 * @author Tomasz Touma
 * @version 1.0
 * @since 1.8
 */
public class StaffForm extends javax.swing.JFrame {

    private int staffID;

    Staff s;
    String url = "jdbc:mysql://127.0.0.1:3306/";
    //database name
    String dbName = "finaleprojectdb";
    //not needed for now

    String userName = "root";
    //password for connecting to local host
    String password = "root";
    Format formatter = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
    }

    public StaffForm(int staffID) {
        initComponents();
        this.staffID = staffID;
        jTextFieldStaffID.setText(String.valueOf(staffID));
        loadStaffDetails();
    }

    /**
     * Loads the details of the staff member with the given {@link #staffID}
     * from the database and populates the corresponding fields in the form.
     * <p>
     * If no record is found, a message dialog will inform the user.
     */
    private void loadStaffDetails() {
        try {

            Connection con = (Connection) DriverManager.getConnection(url + dbName, userName, password);
            String sql = "SELECT first_name,surname,email,phone_number,ppsn,gender,date_of_birth,"
                    + "specializations,address_line_1,address_line_2,county,eircode"
                    + " FROM staff WHERE staff_id=?";

            PreparedStatement prest = con.prepareStatement(sql);
            prest.setInt(1, staffID);

            ResultSet rs = prest.executeQuery();

            if (rs.next()) {

                jTextFieldFirstName.setText(rs.getString("first_name"));
                jTextFieldSurname.setText(rs.getString("surname"));
                jTextFieldEmail.setText(rs.getString("email"));
                jTextFieldPhoneNumber.setText(rs.getString("phone_number"));
                jTextFieldPpsn.setText(rs.getString("ppsn"));
                jComboBoxGender.setSelectedItem(rs.getString("gender"));
                String dob = rs.getString("date_of_birth");
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Adjust the date format as needed
                try {
                    Date date = sdf.parse(dob);
                    Calendar cal = Calendar.getInstance();
                    cal.setTime(date);
                    jDateChooser.setDate(date);
                } catch (ParseException e) {
                    e.printStackTrace(); // Handle the possible parsing error
                }
                jTextFieldSpecializations.setText(rs.getString("specializations"));
                jTextFieldAddress1.setText(rs.getString("address_line_1"));
                jTextFieldAddress2.setText(rs.getString("address_line_2"));
                jTextFieldCounty.setText(rs.getString("county"));
                jTextFieldEircode.setText(rs.getString("eircode"));

            } else {
                // If no data found for the student ID, display a message
                JOptionPane.showMessageDialog(null, "No staff found with ID: " + jTextFieldStaffID.getText());
            }
            rs.close();
            prest.close();
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSave = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldStaffID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAddress1 = new javax.swing.JTextField();
        jTextFieldAddress2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPpsn = new javax.swing.JTextField();
        jTextFieldCounty = new javax.swing.JTextField();
        jTextFieldEircode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSpecializations = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Form");
        setResizable(false);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add, Edit or Delete entry. "));

        jLabel2.setText("StaffID:");

        jTextFieldPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneNumberKeyTyped(evt);
            }
        });

        jTextFieldStaffID.setEditable(false);
        jTextFieldStaffID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldStaffID.setEnabled(false);

        jLabel7.setText("Date of Birth:");

        jLabel8.setText("Address Line 1:");

        jLabel9.setText("Address Line 2:");

        jLabel10.setText("County:");

        jLabel11.setText("Eircode:");

        jLabel12.setText("Phone Number:");

        jLabel3.setText("First Name:");

        jLabel13.setText("Gender:");

        jTextFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFirstNameKeyTyped(evt);
            }
        });

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel4.setText("Surname:");

        jLabel5.setText("Email:");

        jLabel6.setText("PPSN:");

        jTextFieldPpsn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPpsnKeyTyped(evt);
            }
        });

        jTextFieldCounty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCountyKeyTyped(evt);
            }
        });

        jLabel1.setText("Specializations:");

        jTextFieldSpecializations.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSpecializationsKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCounty, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPpsn)
                            .addComponent(jTextFieldStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldSpecializations, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPpsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldSpecializations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldEircode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonPrint)
                    .addComponent(jButtonSave))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * Opens the {@link StaffViewFrame} when the "Search" button is pressed and
     * disposes of the current form.
     */
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        StaffViewFrame svf = new StaffViewFrame();
        svf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * Saves the current staff details entered in the form to the database.
     * <p>
     * Updates the record corresponding to {@link #staffID} with the entered
     * values. A message dialog is shown upon successful update.
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        s = new Staff(jTextFieldFirstName.getText(),
                jTextFieldSurname.getText(), (String) jComboBoxGender.getSelectedItem(), jTextFieldEmail.getText(),
                jTextFieldPpsn.getText(), jTextFieldAddress1.getText(), jTextFieldAddress2.getText(),
                jTextFieldCounty.getText(), jTextFieldEircode.getText(), jTextFieldPhoneNumber.getText(),
                formatter.format(jDateChooser.getDate()), validateInteger(jTextFieldStaffID.getText()), jTextFieldSpecializations.getText());

        try {

            Connection con = (Connection) DriverManager.getConnection(url + dbName, userName, password);
            PreparedStatement prest = null;

            String sql = "UPDATE staff SET  first_name=? ,surname=?"
                    + ",gender=?,email=?,ppsn=?,address_line_1=?,"
                    + " address_line_2=?,county=?, eircode=?"
                    + ", date_of_birth=?, phone_number=?,specializations=? WHERE staff_id=?";

            prest = con.prepareStatement(sql);

            prest.setString(1, s.getFirstName());
            prest.setString(2, s.getSurname());
            prest.setString(3, s.getGender());
            prest.setString(4, s.getEmail());
            prest.setString(5, s.getPpsn());
            prest.setString(6, s.getAddress1());
            prest.setString(7, s.getAddress2());
            prest.setString(8, s.getAddressCounty());
            prest.setString(9, s.getAddressEirCode());
            prest.setString(10, s.getDob());
            prest.setString(11, s.getMobileNumber());
            prest.setString(12, s.getSpecializations());
            prest.setInt(13, s.getStaffID());
            prest.executeUpdate();

            prest.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Staff member has been updated successfully",
                    "Task complite", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException err) {

            System.out.println(err.getMessage());

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Prints the staff member's details to a {@link PrintFrame}.
     * <p>
     * The details include basic personal info, contact information, and
     * specializations.
     */
    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        s = new Staff(jTextFieldFirstName.getText(),
                jTextFieldSurname.getText(), (String) jComboBoxGender.getSelectedItem(), jTextFieldEmail.getText(),
                jTextFieldPpsn.getText(), jTextFieldAddress1.getText(), jTextFieldAddress2.getText(),
                jTextFieldCounty.getText(), jTextFieldEircode.getText(), jTextFieldPhoneNumber.getText(),
                formatter.format(jDateChooser.getDate()), validateInteger(jTextFieldStaffID.getText()), jTextFieldSpecializations.getText());
        PrintFrame spf = new PrintFrame();
        spf.jTextAreaPrint.setText(spf.jTextAreaPrint.getText() + "StudentID: " + s.getStaffID() + "\n"
                + "Name: " + s.getFirstName() + " " + s.getSurname() + "\n"
                + "Email: " + s.getEmail() + "\t\t" + "Phone Number: " + s.getMobileNumber() + "\n"
                + "PPSN: " + s.getPpsn() + "\t\t" + "Gender: " + s.getGender() + "\n"
                + "Date of Birth: " + s.getDob() + "\t\t" + "Specializations: " + s.getSpecializations() + "\n"
                + "Address 1: " + s.getAddress1() + "\t\t" + "Address 2: " + s.getAddress2() + "\n"
                + "County: " + s.getAddressCounty() + "\t\t" + "Eircode: " + s.getAddressEirCode() + "\n");

        spf.setVisible(true);
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTextFieldFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameKeyTyped
        ValidateLetter(evt);
    }//GEN-LAST:event_jTextFieldFirstNameKeyTyped

    private void jTextFieldPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberKeyTyped

    }//GEN-LAST:event_jTextFieldPhoneNumberKeyTyped

    private void jTextFieldPpsnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPpsnKeyTyped
        ValidateDigitAndLetter(evt);
    }//GEN-LAST:event_jTextFieldPpsnKeyTyped

    private void jTextFieldSpecializationsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSpecializationsKeyTyped
        ValidateLetter(evt);
    }//GEN-LAST:event_jTextFieldSpecializationsKeyTyped

    private void jTextFieldCountyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCountyKeyTyped
        ValidateLetter(evt);
    }//GEN-LAST:event_jTextFieldCountyKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAddress1;
    private javax.swing.JTextField jTextFieldAddress2;
    private javax.swing.JTextField jTextFieldCounty;
    private javax.swing.JTextField jTextFieldEircode;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldPpsn;
    private javax.swing.JTextField jTextFieldSpecializations;
    private javax.swing.JTextField jTextFieldStaffID;
    private javax.swing.JTextField jTextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
